# Gitleaks configuration for proactive secret scanning
# Docs: https://github.com/gitleaks/gitleaks

[allowlist]
  description = "allow common false positives"
  files = [
    "test_result.md",
    "yarn.lock",
    "package-lock.json",
    "pnpm-lock.yaml",
    "dist/",
    "build/",
    "__snapshots__/",
  ]

[[rules]]
  id = "generic-api-key"
  description = "Generic API Key"
  regex = '''(?i)(api|access|secret|token|key)[\s\-_]*[:=][\s\-]*["']?([a-z0-9_\-]{16,})["']?'''
  tags = ["key", "api", "generic"]

[[rules]]
  id = "emergent-llm-key"
  description = "Emergent LLM Key pattern"
  regex = '''(?i)sk-emergent-[a-z0-9]{10,}'''
  tags = ["key", "ai", "emergent"]

[[rules]]
  id = "openai-key"
  description = "OpenAI Key pattern"
  regex = '''sk-[A-Za-z0-9]{20,}'''
  tags = ["key", "ai", "openai"]

[[rules]]
  id = "google-api-key"
  description = "Google API key"
  regex = '''AIza[0-9A-Za-z\-_]{35}'''
  tags = ["key", "google"]

[[rules]]
  id = "aws-secret"
  description = "AWS Secret Access Key"
  regex = '''(?i)aws(.{0,20})?(secret|sk|access)[^A-Za-z0-9\n]{0,3}[A-Za-z0-9\/+=]{40}'''
  tags = ["key", "aws"]

[[rules]]
  id = "password-in-code"
  description = "Hardcoded password"
  regex = '''(?i)(password|pass|pwd)[\s\-_]*[:=][\s\-]*["'][^"'\n]{6,}["']'''
  tags = ["password"]